//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMSGuildExtractor.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KMSGuildExtractor.Localization.LocalizationString", typeof(LocalizationString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 내보내기.
        /// </summary>
        public static string button_extract_data {
            get {
                return ResourceManager.GetString("button_extract_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유저정보 불러오기.
        /// </summary>
        public static string button_load_data {
            get {
                return ResourceManager.GetString("button_load_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 길드원.
        /// </summary>
        public static string guild_position_member {
            get {
                return ResourceManager.GetString("guild_position_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 마스터.
        /// </summary>
        public static string guild_position_owner {
            get {
                return ResourceManager.GetString("guild_position_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 부마스터.
        /// </summary>
        public static string guild_position_staff {
            get {
                return ResourceManager.GetString("guild_position_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 길드원 목록 가져오기.
        /// </summary>
        public static string guild_submit {
            get {
                return ResourceManager.GetString("guild_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepi.
        /// </summary>
        public static string info_author_name {
            get {
                return ResourceManager.GetString("info_author_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 샤레니안의 악마.
        /// </summary>
        public static string info_image_tooltip {
            get {
                return ResourceManager.GetString("info_image_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 길드 이름.
        /// </summary>
        public static string input_name_guild {
            get {
                return ResourceManager.GetString("input_name_guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버.
        /// </summary>
        public static string input_name_server {
            get {
                return ResourceManager.GetString("input_name_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색하기.
        /// </summary>
        public static string input_search {
            get {
                return ResourceManager.GetString("input_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 잘못된 길드 이름입니다..
        /// </summary>
        public static string input_wrong_guild_name {
            get {
                return ResourceManager.GetString("input_wrong_guild_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 완료.
        /// </summary>
        public static string load_done {
            get {
                return ResourceManager.GetString("load_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 준비됨.
        /// </summary>
        public static string load_ready {
            get {
                return ResourceManager.GetString("load_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터를 동기화하는 중.
        /// </summary>
        public static string load_syncing {
            get {
                return ResourceManager.GetString("load_syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터를 불러오는 중.
        /// </summary>
        public static string load_working {
            get {
                return ResourceManager.GetString("load_working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터를 불러오지 못했습니다..
        /// </summary>
        public static string search_error {
            get {
                return ResourceManager.GetString("search_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색 중 입니다....
        /// </summary>
        public static string search_ing {
            get {
                return ResourceManager.GetString("search_ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색결과가 없습니다..
        /// </summary>
        public static string search_no_result {
            get {
                return ResourceManager.GetString("search_no_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 레벨.
        /// </summary>
        public static string search_result_level {
            get {
                return ResourceManager.GetString("search_result_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이름.
        /// </summary>
        public static string search_result_name {
            get {
                return ResourceManager.GetString("search_result_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 월드.
        /// </summary>
        public static string search_result_world {
            get {
                return ResourceManager.GetString("search_result_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메이플 길드 유저정보 추출기.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 창 닫기.
        /// </summary>
        public static string titlebar_close {
            get {
                return ResourceManager.GetString("titlebar_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 창 최소화.
        /// </summary>
        public static string titlebar_minimize {
            get {
                return ResourceManager.GetString("titlebar_minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최신 버전이에요 :D.
        /// </summary>
        public static string updatenotify_already_updated {
            get {
                return ResourceManager.GetString("updatenotify_already_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새로운 업데이트가 있는지 확인하는 중....
        /// </summary>
        public static string updatenotify_check_update {
            get {
                return ResourceManager.GetString("updatenotify_check_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설치하기.
        /// </summary>
        public static string updatenotify_install_new_version {
            get {
                return ResourceManager.GetString("updatenotify_install_new_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새로운 버전이 있어요!.
        /// </summary>
        public static string updatenotify_new_version_update {
            get {
                return ResourceManager.GetString("updatenotify_new_version_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아케인.
        /// </summary>
        public static string world_arcane {
            get {
                return ResourceManager.GetString("world_arcane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오로라.
        /// </summary>
        public static string world_aurora {
            get {
                return ResourceManager.GetString("world_aurora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 베라.
        /// </summary>
        public static string world_bera {
            get {
                return ResourceManager.GetString("world_bera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 버닝.
        /// </summary>
        public static string world_burning {
            get {
                return ResourceManager.GetString("world_burning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 버닝2.
        /// </summary>
        public static string world_burning2 {
            get {
                return ResourceManager.GetString("world_burning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 크로아.
        /// </summary>
        public static string world_croa {
            get {
                return ResourceManager.GetString("world_croa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 엘리시움.
        /// </summary>
        public static string world_elysium {
            get {
                return ResourceManager.GetString("world_elysium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이노시스.
        /// </summary>
        public static string world_enosis {
            get {
                return ResourceManager.GetString("world_enosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 루나.
        /// </summary>
        public static string world_luna {
            get {
                return ResourceManager.GetString("world_luna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 노바.
        /// </summary>
        public static string world_nova {
            get {
                return ResourceManager.GetString("world_nova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리부트.
        /// </summary>
        public static string world_reboot {
            get {
                return ResourceManager.GetString("world_reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리부트2.
        /// </summary>
        public static string world_reboot2 {
            get {
                return ResourceManager.GetString("world_reboot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 레드.
        /// </summary>
        public static string world_red {
            get {
                return ResourceManager.GetString("world_red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스카니아.
        /// </summary>
        public static string world_scania {
            get {
                return ResourceManager.GetString("world_scania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유니온.
        /// </summary>
        public static string world_union {
            get {
                return ResourceManager.GetString("world_union", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 제니스.
        /// </summary>
        public static string world_zenith {
            get {
                return ResourceManager.GetString("world_zenith", resourceCulture);
            }
        }
    }
}
